const products = [
    {
        _id: "1",
        name: "Sitting Chair",
        image:"https://images.pexels.com/photos/2082090/pexels-photo-2082090.jpeg?auto=compress&cs=tinysrgb&w=600",
        description: "A chair is a type of seat, typically designed for one person and consisting of one or more legs, a flat or slightly angled seat and a back-rest. It may be made of wood, metal, or synthetic materials, and may be padded or upholstered in various colors and fabrics.",
        brand: "Furniture world",
        category: "Furniture",
        price: 899.99,
        countInstock: 15,
        rating: 1.5,
        numReviews: 20,
    },
    {
        _id: "2",
        name: "Home Sofa",
        image: "https://images.pexels.com/photos/1248583/pexels-photo-1248583.jpeg?auto=compress&cs=tinysrgb&w=600",
        description: "A sofa's suspension system can contribute to its comfort and durability. Common suspension types include coiled spring units, serpentine or no-sag springs, and elastabelt webbing",
        brand: "furniture world",
        category: "Futurniture",
        price: 499.99,
        countInstock: 15,
        rating: 4.0,
        numReviews: 5,
    },
    {
        _id: "3",
        name: "Wooden Bed",
        image: "https://images.pexels.com/photos/775219/pexels-photo-775219.jpeg?auto=compress&cs=tinysrgb&w=600",
        description: " Wooden beds are built with solid natural materials, their sturdy composition mean they are incredibly durable and not easily damaged. In fact, unlike other bed frames that can require a lot more upkeep, a wooden bed can thrive for years",
        brand: "furniture world",
        category: "Futurniture",
        price: 699.99,
        countInstock: 15,
        rating: 2.0,
        numReviews: 9,
    },
    {
        _id: "4",
        name: "Cushion Chairs",
        image: "https://images.pexels.com/photos/923192/pexels-photo-923192.jpeg?auto=compress&cs=tinysrgb&w=600",
        description: "Ergonomically designed velvet chair for home with a lacquered finish, heavy-duty armrest, back and seat cushion made up of velvet upholstery and PU material for maximum comfort;Sturdy Legs: The chair comes with strong legs which ensure its durability.",
        brand: "Damro Furnitures",
        category: "Futurniture",
        price: 899.00,
        countInstock: 15,
        rating: 4.0,
        numReviews: 50,
    },
    {
        _id: "5",
        name: "Comfort Bed",
        image: "https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg?auto=compress&cs=tinysrgb&w=600",
        description: "ComfyBed is a woodchip bedding product for horses that is dry, absorbent, and virtually dust-free. It's designed to be comfortable, long-lasting, and free-draining, and it stays dry on top. ComfyBed is also biodegradable and low maintenance. ",
        brand: "Comfy Furnitures",
        category: "Futurniture",
        price: 1299.28,
        countInstock: 15,
        rating: 3.0,
        numReviews: 6,
    },
    {
        _id: "6",
        name: "TV Showcase",
        image: "https://images.pexels.com/photos/1648771/pexels-photo-1648771.jpeg?auto=compress&cs=tinysrgb&w=600",
        description: "TV stands, also referred to as TV consoles, are furniture items used to hold the television above the floor at a comfortable viewing height for a seated viewer. Typically used in residential living rooms, most TV stands provide additional storage options such as shelves and drawers ",
        brand: "Damro Furnitures",
        category: "Futurniture",
        price: 799.00,
        countInstock: 15,
        rating: 5.0,
        numReviews: 10,
    },
    {
        _id: "7",
        name: "Resting chair",
        image: "https://images.pexels.com/photos/276534/pexels-photo-276534.jpeg?auto=compress&cs=tinysrgb&w=600",
        description: "Resting chairs, also known as relaxation chairs, recliners, and loungers, are designed to be comfortable and supportive, and to help you relax and unwind. ",
        brand: "Damro Furnitures",
        category: "Futurniture",
        price: 819.99,
        countInstock: 15,
        rating: 3.5,
        numReviews: 12,
    },
    {
        _id: "8",
        name: "Coffee Table",
        image: "https://images.pexels.com/photos/2387754/pexels-photo-2387754.jpeg?auto=compress&cs=tinysrgb&w=600",
        description: "A coffee table is a low table designed to be placed in a sitting area for convenient support of beverages, remote controls, magazines, books (especially large, illustrated coffee table books), decorative objects, and other small items. ",
        brand: "Damro Furnitures",
        category: "Futurniture",
        price: 190.99,
        countInstock: 15,
        rating: 4.0,
        numReviews: 1,
    },
]

export default products